spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhth?characterEncoding=utf8&useSSL=true
    username: root
    password: -------
    tomcat:
      validation-query: select 1
    type: org.apache.tomcat.jdbc.pool.DataSource

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
     ddl-auto: update
  jackson:
    serialization: true # 初始化为json格式
  thymeleaf:
      mode: LEGACYHTML5   #LEGACYHTML5需要搭配一个额外的库NekoHTML才可用
      cache: false
server:
  port : 80
  context-path: /bom
